### ISSUE TITLE
Use github pages to show the contents of this repo?

### ISSUE THREAD

**Issue by yfzhe** [schemedoc/bibliography#1]
It maybe is a better way to present these documents.

**Comment by amirouche** [comment]
Thanks for you interest.

> It maybe is a better way to present these documents.

I am thinking about improving the situation. 

One page per paper with title, keywords and abstract with the possibility to add comments to each paper.

That is a lot of work.

**Comment by lassik** [comment]
We may have the chance to host them under scheme.org later this year.

**Comment by lassik** [comment]
Now at https://research.scheme.org/ (_Bibliography_ section).

You will notice that the Research front page is a mess. Help would be very much welcome.

**Comment by lassik** [comment]
> possibility to add comments to each paper

This is an interesting idea. Let's open another issue about it.
